### ISSUE TITLE
habilitado

### ISSUE THREAD

**Issue by cleomenes** [cleomenes/Monitoria#3]
função que vai verificar se as transições estão habilitadas

**Comment by cleomenes** [comment]
vai precisar dos tokens de cada lugar, e dos arcos consumidores, e vai apenas comparar se as tokens < arcos(i, T), se for for verdade essa condição a transição não esta habilitada

**Comment by cleomenes** [comment]
duvidas?

**Comment by cleomenes** [comment]
coloquei o T assim maiusculo para dizer que é fixo, enquanto vc analiza ele em relação a todos os lugares de onde ele recebe

**Comment by guilhermediasl** [comment]
No caso a função retorna 0 ou 1?
